wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.6
    framework: huggingface
    huggingface_version: 4.44.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1723779232
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 105
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 105
      3:
      - 2
      - 23
      4: 3.8.19
      5: 0.17.6
      6: 4.44.0
      8:
      - 1
      - 5
      13: linux-x86_64
